version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "9008:8080"
    volumes:
      - "~/ipa-server-data:/app/upload"
