version: "2"

services:
  web:
    build: .
    container_name: ipa-server
    restart: always
    environment:
      - NODE_ENV=production
      - USE_HTTPS=true
      - CERT_LOCATION=/app/certificate
    ports:
      - "5000:8080"
    volumes:
      - "~/ipa-server-data:/app/upload"
      - "/etc/nginx/ipa_server:/app/certificate"
